name: CI-Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: prep
      run: mkdir runs

    - name: rm-test
      run: pwd
      run: cd src/rm
      run: make rm_test
      run: make clean_test
